### ISSUE TITLE
Docs Images

### ISSUE THREAD

**Issue by Luijinho** [JuezLTI/IO2_Documentation#5]
Should we replicate the images stored in the docs folder for each language?
For example, create an equivalent image in Portuguese, Spanish...

![explainWhy](https://user-images.githubusercontent.com/67716453/194703369-1eb0ec85-6e79-4343-b8c4-f244009cbc15.png)

**Comment by albsierra** [comment]
My initial intention was to share the same images between languages. So, I guess you don't need translate them and make a new image.
