### ISSUE TITLE
Image blurred

### ISSUE THREAD

**Issue by albsierra** [JuezLTI/IO2_Documentation#6]
The [image belonging to PEARL schema](https://github.com/JuezLTI/IO2_Documentation/blob/c855defd79cad1638be70e4309da29a4b1c2d2b1/MOOC2/Development/API/PEARL/PEARL.png) is blurred and it should be changed by a new one.

**Comment by zpleal** [comment]
I redid it as a UML class diagram and exported in SVN format.
